apiVersion: apps/v1
kind: Deployment
metadata:
  name: ggj-connection-service
  labels:
    app: ggj-connection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ggj-connection-service
  template:
    metadata:
      labels:
        app: ggj-connection-service
    spec:
      containers:
      - name: ggj-connection-service
        image: ggj-connection-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "connections_db"
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
